language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test -- --coverage --no-cache --runInBand
after_success:
  - yarn global add coveralls
  - cat coverage/remapped/lcov.info | coveralls
